#!/bin/sh

set -e

if [ "$1" = "purge" ] ; then
        if getent passwd gnome-initial-setup >/dev/null; then
                if which deluser >/dev/null 2>&1; then
                        deluser --system gnome-initial-setup || echo "Could not remove gnome-initial-setup user."
                fi
        fi
fi
#DEBHELPER#
exit 0
