#!/usr/bin/env python3
# eos-setup-live-user - adds eos-installer icons to a newly-created account
# Copyright (C) 2016-2017 Endless Mobile, Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

import argparse
import glob
import json
import logging
import os
import subprocess
import sys
import tempfile

from gi.repository import GLib, Gio

log = logging.getLogger(sys.argv[0])

ICON_GRID_DIR = '/var/lib/eos-image-defaults/icon-grid'

DESKTOP_GRID_ID = 'desktop'

EOS_INSTALLER = 'com.endlessm.Installer.desktop'
GDM_APPS_DIR = '/usr/share/gdm/greeter/applications'
EOS_INSTALLER_PATH = os.path.join(GDM_APPS_DIR, EOS_INSTALLER)
LOCAL_APPS_DIR = '/usr/local/share/applications'
LOCAL_DESKTOP_PATH = os.path.join(LOCAL_APPS_DIR, EOS_INSTALLER)

GOOGLE_CHROME = 'google-chrome.desktop'
CHROMIUM_BROWSER = 'chromium-browser.desktop'

LIVE_SETTINGS_DB = '/var/lib/eos-image-defaults/settings.live'
USER_PROFILE_PATH = '/usr/local/share/dconf/profile/user'
USER_PROFILE = '''user-db:user
file-db:/var/lib/eos-image-defaults/settings.live
file-db:/var/lib/eos-image-defaults/settings
'''

SHELL_SCHEMA = 'org.gnome.shell'
FAVORITE_APPS_KEY = 'favorite-apps'

GS_SCHEMA = 'org.gnome.software'
ALLOW_UPDATES = 'allow-updates'


class AdjustGSettings(object):
    def __init__(self):
        self.keyfile = GLib.KeyFile()

    def update(self, schema, key, variant):
        value = variant.print_(False)
        log.info('Updating %s: %s to %s', schema, key, value)
        self.keyfile.set_string(schema.replace('.', '/'), key, value)

    def prepare(self):
        self.update_favorite_apps()
        self.disallow_app_center_updates()

    def write_dconf_compile(self):
        '''Write a new system-wide settings database with the overridden
        settings, and adjust the user profile to use it.'''
        with tempfile.TemporaryDirectory(suffix='.d') as d:
            keyfile_path = os.path.join(d, '00-live')
            log.info('writing keyfile to %s', keyfile_path)
            self.keyfile.save_to_file(keyfile_path)

            os.makedirs(os.path.dirname(LIVE_SETTINGS_DB), exist_ok=True)

            args = ['dconf', 'compile', LIVE_SETTINGS_DB, d]
            log.info('$ %s', ' '.join(args))
            subprocess.check_call(args)

        log.info('Installing new DConf profile to %s', USER_PROFILE_PATH)
        os.makedirs(os.path.dirname(USER_PROFILE_PATH), exist_ok=True)
        with open(USER_PROFILE_PATH, 'w') as f:
            f.write(USER_PROFILE)

    def write_stdout(self):
        '''Just write the keyfile used by `dconf compile` to stdout.
        For debugging purposes only.'''
        data, length = self.keyfile.to_data()
        print(data)

    def update_favorite_apps(self):
        settings = Gio.Settings(schema=SHELL_SCHEMA)
        favorite_apps = settings.get_strv(FAVORITE_APPS_KEY)
        changed = False

        # Prepend installer icon
        if EOS_INSTALLER not in favorite_apps:
            favorite_apps.insert(0, EOS_INSTALLER)
            changed = True

        # Replace Chrome (downloaded on demand) with Chromium (pre-installed).
        # This effectively undoes a step taken in the image builder,
        # pre-seeding /var/eos-image-defaults/settings with the opposite
        # change.
        if replace_chrome_with_chromium(favorite_apps):
            changed = True

        if changed:
            self.update(SHELL_SCHEMA, FAVORITE_APPS_KEY,
                        GLib.Variant('as', favorite_apps))

    def disallow_app_center_updates(self):
        self.update(GS_SCHEMA, ALLOW_UPDATES, GLib.Variant('b', False))


def install_desktop_file():
    """eos-installer is shipped in all images, but its desktop file is
    (deliberately) only present in the GDM greeter's environment. For
    image-booted live sessions, we symlink it into place."""
    if not os.path.exists(LOCAL_DESKTOP_PATH):
        log.info('ensuring %s exists', LOCAL_APPS_DIR)
        os.makedirs(LOCAL_APPS_DIR, exist_ok=True)

        log.info('symlinking %s to %s', EOS_INSTALLER, LOCAL_DESKTOP_PATH)
        os.symlink(EOS_INSTALLER_PATH, LOCAL_DESKTOP_PATH)


def replace_chrome_with_chromium(apps):
    if GOOGLE_CHROME in apps:
        apps[apps.index(GOOGLE_CHROME)] = CHROMIUM_BROWSER
        return True
    else:
        return False


def remove_chrome_from_icon_grids():
    log.info("Restoring Chromium to icon grids, if needed")

    pattern = os.path.join(ICON_GRID_DIR, 'icon-grid-*.json')
    for path in glob.glob(pattern):
        log.info("Checking %s", path)
        try:
            with open(path, 'r') as f:
                grid = json.load(fp=f)

            if replace_chrome_with_chromium(grid[DESKTOP_GRID_ID]):
                log.info("Updating %s", path)

                with open(path, 'w') as f:
                    json.dump(grid, fp=f)
        except Exception:
            log.exception("while processing %s", path)


def prepend_installer_to_icon_grid():
    log.info("Adding installer icon to the desktop")

    pattern = os.path.join(ICON_GRID_DIR, 'icon-grid-prepend-*.json')
    c_path = os.path.join(ICON_GRID_DIR, 'icon-grid-prepend-C.json')
    paths = glob.glob(pattern)
    if c_path not in paths:
        paths.append(c_path)

    for path in paths:
        try:
            try:
                with open(path, 'r') as f:
                    log.info("reading existing file %s", path)
                    grid = json.load(fp=f)
            except FileNotFoundError:
                log.info("%s doesn't exist (as expected)", path)
                grid = {}

            desktop = grid.setdefault(DESKTOP_GRID_ID, [])
            if EOS_INSTALLER not in desktop:
                desktop.insert(0, EOS_INSTALLER)

                log.info("Writing %s: %s", path, json.dumps(obj=grid))
                with open(path, 'w') as f:
                    json.dump(obj=grid, fp=f)
        except Exception:
            log.exception("while processing %s", path)


def main():
    p = argparse.ArgumentParser(
        description='Configures system settings for live session')
    p.add_argument('--dry-run', action='store_true',
                   help='Just print the DConf keyfile to stdout')
    a = p.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format='%(name)s:%(lineno)-3s %(funcName)20s %(levelname)7s: '
               '%(message)s')

    setup = AdjustGSettings()
    setup.prepare()

    if a.dry_run:
        setup.write_stdout()
    else:
        setup.write_dconf_compile()

        install_desktop_file()
        remove_chrome_from_icon_grids()
        prepend_installer_to_icon_grid()


if __name__ == '__main__':
    main()
